### ISSUE TITLE
Is this capable of bypassing bot detections such as Imperva?

### ISSUE THREAD

**Issue by OwaisSiddiqui** [Xetera/jiu#2]
I saw this and really want to use it. However, the site I am scraping has a bot detection system from Imperva. The only way I can bypass it is by using Puppeteer (not headless). I was wondering if this is capable of bypassing such systems.

**Comment by Xetera** [comment]
No, if I run into problems with problematic level bot detection I could look into reverse engineering a solution but so far I haven't come across any and I'm very doubtful that I will since I'm not trying to scrape any high importance data.

If you're looking to defeat bot protection you're probably trying to make some kind of monitor and this is not the repository for it, since pages are scraped on average once every 1-2 days.

**Comment by OwaisSiddiqui** [comment]
I also needed it to scrape every 1 - 2 days but the bot detection system triggers anytime I connect to the webpage without a real browser opening (e.g. Chromium from Puppeteer). I was hoping maybe your scraper was manipulating things like User Agents string to make it seem like a real browser, but I guess that's a whole different problem to solve.

Thank you for the response. I guess I'll look elsewhere.

**Comment by OwaisSiddiqui** [comment]
I also needed it to scrape every 1 - 2 days but the bot detection system triggers anytime I connect to the webpage without a real browser opening (e.g. Chromium from Puppeteer). I was hoping maybe your scraper was manipulating things like User Agents string to make it seem like a real browser, but I guess that's a whole different problem to solve.

Thank you for the response. I guess I'll look elsewhere.
